### ISSUE TITLE
definition of shape and pose parameter 

### ISSUE THREAD

**Issue by Pyf1234** [lixiny/manotorch#4]
I'm trying to convert (rotation angles,size of the rigid body) to mano-hand mesh using the mano-layer you provided.
But my definition of hand asset is in mujoco (.xml) format and definition of rotation is in (rotation angles of the joints around local x,y,z axis)
So in order to apply the model you provided to my data,I need to figure out the exact definition of shape and pose parameter of manolayer.
![image](https://user-images.githubusercontent.com/92667266/231378200-f8d2c4f6-459f-40a7-a5aa-f5f0f89ff43b.png)
Could you please provide me with the exact definition or provide me with some material related to it.
Thanks a lot!

**Comment by lixiny** [comment]
Hi, if you already have the euler angles of each joints/articulation on the hand, you can follow the joint orders described in [compose](https://github.com/lixiny/manotorch/blob/9515773ffe1ca26f2d4effd4b7fe2796c8f244e7/manotorch/axislayer.py#L112) to customize your hand pose. 


demo example [here](scripts/simple_compose.py)

In order to dive deep of the  shape and pose parameter defined in original MANO, 
you can visit paper:  Embodied Hands: Modeling and Capturing Hands and Bodies Together.

As for the demo code in your screenshot, it is just a bare demo of how the manolayer was called. We use the use_pca=True to use the low-dimensional 15 PCA pose components to control the total 15 joints (45 DoFs in MANO). 

Best,
Lixin

**Comment by Pyf1234** [comment]
Thanks for your reply.
By the way I have another question about this code .
![image](https://user-images.githubusercontent.com/92667266/231428050-e41ec3d9-ca06-43dc-8d96-ecadf9ccd0d4.png)
The intermediate tensor close_face is not moved to "cuda",so I guess the manolayer module could not run on GPU if I don't manually modify the code?

**Comment by DakshDeepakTI** [comment]
Hi, I found this thread somewhat helpful, thank you. 
However, I'm encountering an issue with my approach. I'm utilizing 21 keypoints (x, y, z) to construct vectors and calculating angles across different axes by projecting onto the XY, YZ, and ZX planes. Then, I use the compose function to generate a mesh using MANO, but the mesh output closely matches only a few datasets from MANO. Currently, I'm only employing the pose parameter for this purpose and not the shape parameters.
Just want to check is this approach right?
